### ISSUE TITLE
Large Bundle Rejection with builders list added on eth_sendBundle

### ISSUE THREAD

**Issue by rileyg98** [flashbots/rbuilder#162]
Attempting to move multiplex bundling to the Flashbots relay with builders list in eth_sendBundle with a large bundle results in an RPC error with the message "invalid bundle body size". 

Is there a limitation on bundle size with Flashbots? 

The bundle is pretty large as it includes 50+ txns including a contract creation - it used 16M gas. However, eth_simulateBundle works fine, and my old method of submitting bundles works correctly, however I haven't checked if Flashbots reports a successful bundle receive. This makes me think that there may be an Order size limit in your database? 

My look into the order code shows that builders isn't parsed there.

**Comment by metachris** [comment]
eth_sendBundle does not support a list of builders. Here's the API spec: https://docs.flashbots.net/flashbots-auction/advanced/rpc-endpoint#eth_sendbundle

Closing the issue.

**Comment by rileyg98** [comment]
Um, in the spec linked, it shows it does.

**Comment by rileyg98** [comment]
Following up from that, this is the eth_sendBundle API from that link:

{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "eth_sendBundle",
  "params": [
    {
      txs,               // Array[String], A list of signed transactions to execute in an atomic bundle
      blockNumber,       // String, a hex encoded block number for which this bundle is valid on
      minTimestamp,      // (Optional) Number, the minimum timestamp for which this bundle is valid, in seconds since the unix epoch
      maxTimestamp,      // (Optional) Number, the maximum timestamp for which this bundle is valid, in seconds since the unix epoch
      revertingTxHashes, // (Optional) Array[String], A list of tx hashes that are allowed to revert
      replacementUuid,   // (Optional) String, UUID that can be used to cancel/replace this bundle
      builders,          // (Optional) Array[String], A list of [registered](https://github.com/flashbots/dowg/blob/main/builder-registrations.json) block builder names to share the bundle with **<----- this is the builder list**
    }
  ]
}
(Sorry the code formatting didn't play nice)

There's an entire sub-part to that API endpoint on if the bundle includes it, there'll be an additional boolean. I'm also actively using it with smaller bundles.

**Comment by rileyg98** [comment]
@metachris sorry to tag you but this is not closed or resolved by your reply
