### ISSUE TITLE
sepoilia ; Failed to get parent header for new slot: Block header not found ;  Watchdog timeout

### ISSUE THREAD

**Issue by Leoounardo** [flashbots/rbuilder#217]
Hi, I followed the step-by-step instructions to run beacon lighthouse and reth, they both synced and now I'm trying to run rbuilder. However, all I get from the builder is:

> 2024-10-16T18:40:21.500359Z WARN rbuilder::live_builder: Failed to get parent header for new slot: Block header not found

and after some time, rbuilder exits:

> 2024-10-16T18:40:34.776586Z ERROR rbuilder::live_builder::watchdog: Watchdog timeout.

If anyone can give me some light, I'd appreciate it!!
```

**rbuilder: config-live.toml:**
log_json = false
log_level = "info,rbuilder=debug"

chain = "sepolia"
reth_datadir = "/home/leo/.local/share/reth/sepolia/"

coinbase_secret_key = "_"
relay_secret_key = "_"
optimistic_relay_secret_key = "_"

# cl_node_url can be a single value, array of values, or passed by an environment variables with values separated with a comma
# cl_node_url = "http://localhost:8002"
cl_node_url = ["http://localhost:8002"]
jsonrpc_server_port = 8017
jsonrpc_server_ip = "localhost"
el_node_ipc_path = "/tmp/reth.ipc"
extra_data = "lamed"

#blocklist_file_path = "./blocklist.json"

# dry_run = false
# dry_run_validation_url = "http://localhost:8545"

ignore_cancellable_orders = true

max_concurrent_seals = 4

genesis_fork_version = "0x90000069"

sbundle_mergeabe_signers = []
# slot_delta_to_start_submits_ms is usually negative since we start bidding BEFORE the slot start
# slot_delta_to_start_submits_ms = -5000
live_builders = ["mp-ordering"]

[[relays]]
name = "flashbots"
url = "https://boost-relay-sepolia.flashbots.net"
priority = 1
use_ssz_for_submit = false
use_gzip_for_submit = false

[[builders]]
name = "mgp-ordering"
algo = "ordering-builder"
discard_txs = true
sorting = "mev-gas-price"
failed_order_retries = 1
drop_failed_orders = true

[[builders]]
name = "mp-ordering"
algo = "ordering-builder"
discard_txs = true
sorting = "max-profit"
failed_order_retries = 1
drop_failed_orders = true
```

> reth node --full --chain sepolia --http --http.port 8029 --authrpc.addr 127.0.0.1 --authrpc.port 8001 --authrpc.jwtsecret /secrets/jwt.hex  --log.file.directory="/home/leo/rethlog/"

**lighthouse beacon:**

> lighthouse bn --network sepolia --execution-endpoint http://localhost:8001 --execution-jwt /secrets/jwt.hex --checkpoint-sync-url https://beaconstate-sepolia.chainsafe.io --http-port 8002  --http --disable-deposit-contract-sync --port 9005 --port6 9020  --always-prepare-payload --prepare-payload-lookahead 8000 --logfile /home/leo/lighthouselog.txt --suggested-fee-recipient 0x1102E22fF1F6F56Ed1B2E042959B5Ee90c62A29c --builder https://boost-relay-sepolia.flashbots.net

**Comment by Leoounardo** [comment]
this work, but rbuilder no... :(

`root@brd:~/rbuilder# reth db --datadir /home/leo/.local/share/reth/sepolia/ get mdbx HeaderNumbers 0x6c424b465fed805b3c79aeafb43d12ee688866baf00e29fea71110fc3026d401`

```
2024-10-19T15:57:51.997998Z  INFO Initialized tracing, debug log directory: /home/leo/.cache/reth/logs/mainnet
2024-10-19T15:57:52.036249Z  INFO Opening storage db_path="/home/leo/.local/share/reth/sepolia/db" sf_path="/home/leo/.local/share/reth/sepolia/static_files"
2024-10-19T15:57:52.039891Z  INFO Verifying storage consistency.

6904931
```

**Comment by dallonby** [comment]
I had the same problem. I needed to use --engine.legacy switch on latest version of Reth to get it to work.
