### ISSUE TITLE
Rollup Boost Support

### ISSUE THREAD

**Issue by 0xgregthedev** [flashbots/rbuilder#247]
https://github.com/flashbots/rollup-boost

I was wondering if there would be any interest in adding block building support for L2s via the rollup-boost approach, and if so begin a discussion on the best way to approach this.

**Comment by ferranbt** [comment]
Hi! Rollup-boost does not require any changes in the builder to work. You could use our [reth-rbuilder](https://github.com/flashbots/rbuilder/tree/develop/crates/reth-rbuilder) integrated binary as an external builder already.
