### ISSUE TITLE
[wiki] broken link for config-backtest-example.toml

### ISSUE THREAD

**Issue by mralj** [flashbots/rbuilder#313]
In the [Noob Guide for Backtesting](https://github.com/flashbots/rbuilder/wiki/Noob-Guide-for-Backtesting) the link navigating to `config-backtest-example.toml` is broken. 
It is: 
[https://github.com/flashbots/rbuilder/blob/main/config-backtest-example.toml](https://github.com/flashbots/rbuilder/blob/main/config-backtest-example.toml), but it should be [https://github.com/flashbots/rbuilder/blob/develop/config-backtest-example.toml](https://github.com/flashbots/rbuilder/blob/develop/config-backtest-example.toml)

It's not much, but it's honest work 😅

**Comment by ferranbt** [comment]
Hey, thank you for the issue. Do you want to open a PR?

**Comment by mralj** [comment]
AFAIK I can't ([link](https://stackoverflow.com/questions/10642928/how-can-i-make-a-pull-request-for-a-wiki-page-on-github)) or am I missing something? 

There are some suggestions with forking wikis but just opening the issue looked much simpler :)
